---
# | ............................................................................
# | Config Ansible
# | ............................................................................

# | ······ Set Domain URL
wpDomain          : 'mywordpress.local'

# | ······ MySQL Config
mysqlUser         : 'root'
mysqlPass         : 'vagrant'
mysqlTemplatePath : 'templates/my.cnf'

# | ······ MySQL Database
dbName            : 'wordpress'
dbUser            : 'wordpress'
dbPass            : 'vagrant'

# | ······ Wordpress Config
wp_path           : '/home/vagrant/www'
wordpressTemPath  : 'templates/wp-config.php'
vhostTemplatePath : 'templates/vhost.conf'

# | ······ Vagrant User and Group
home              : '/home/vagrant'
owner             : 'vagrant'
group             : 'vagrant'


# | ............................................................................
# | ### Config VirtualBox VM
# | ............................................................................

vms:
  - name               : vag-lamp
    box                : bento/ubuntu-16.04
    box_version        : 2.2.9
    box_check_update   : false
    ram                : 2048
    cpus               : 2

  # | ······ Defining Netword
    network :
      ip_private       : 192.168.70.99
      ip_public        : 10.0.0.99
      bridge           : 'eth0'

  # | ······ Defining a Forwarded Port
    ports :

      - guest          : 8080
        host           : 8080

      - guest          : 8088
        host           : 8088

  # | ······ Config Synced folders
    syncDir :
      - host           : share
        guest          : /home/vagrant/share
        dmode          : 766
        fmode          : 766

      - host           : www
        guest          : /home/vagrant/www
        owner          : www-data
        group          : www-data
        dmode          : 775
        fmode          : 775

      - host           : html
        guest          : /home/vagrant/html
        owner          : www-data
        group          : www-data
        dmode          : 775
        fmode          : 775

  # | ······ Ansible privision
    ansible :
      verbose          : v
      playbook         : ansible/playbook.yaml
      inventory_path   : ansible/inventory
      host_key_checking: false
      limit            : all

  # | ······ GUI
      # gui              : true

  # | ······ Bash privision
      # bash             : bash/init.sh

  # | ······ Puppet privision
      # puppet           : init.pp

# ..............................................................................
