---

# | ······ Set Domain URL
wpDomain          : 'mywordpress.local'

# | ······ MySQL Config
mysqlUser         : 'root'
mysqlPass         : 'vagrant'
mysqlTemplatePath : 'templates/my.cnf'

# | ······ MySQL Database
dbName            : 'wordpress'
dbUser            : 'wordpress'
dbPass            : 'vagrant'

# | ······ Wordpress Config
wordpressPath     : '/home/vagrant/www'
wordpressTemPath  : 'templates/wp-config.php'
vhostTemplatePath : 'templates/vhost.conf'

# | ······ Vagrant User and Group
home              : '/home/vagrant'
owner             : 'vagrant'
group             : 'vagrant'
